apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: warm-eks-cluster
  version: "1.29"
  region: ap-northeast-2

vpc:
  subnets:
    public:
      public-a: { id: subnet-0114e97320133cfd0 }
      public-b: { id: subnet-0ff877124fa03b19a }
    private:
      private-a: { id: subnet-0556b862aa0f17b7a }
      private-b: { id: subnet-01b83b34eff432604 }

iamIdentityMappings:
  - groups: system:masters
    rolearn: arn:aws:iam::073762821266:root
    username: admin
    noDuplicateARNs: true # prevents shadowing of ARNs

iam:
  withOIDC: true
  
managedNodeGroups:
  - name: warm-node-group
    labels: { app: warm }
    instanceType: m5.large
    instanceName: warm-node-instance
    desiredCapacity: 2
    minSize: 2
    maxSize: 20
    privateNetworking: true
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        cloudWatch: true
        awsLoadBalancerController: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
